version: '3'
services:
  db:
    image: 'mariadb:latest'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: baro
      MYSQL_DATABASE: baro
      MYSQL_USER: baro
      MYSQL_PASSWORD: baro
    ports:
      - '3306:3306'
    volumes:
      - './.mariadb:/var/lib/mysql'
